import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Footer from './Footer'
// For App Router (src/app/layout.js)

import { Poppins,Montserrat  } from 'next/font/google'

const poppins = Poppins({
  weight: ['400', '700'], // Choose the weights you want
  subsets: ['latin'],
  variable: '--font-poppins', // CSS variable name
});

const montserrat = Montserrat({
  weight: ['400', '700'], // Choose the weights you want
  subsets: ['latin'],
  variable: '--font-montserrat', // CSS variable name
});



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${montserrat.variable}`}>
      <body>
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}